# Generated by Django 6.0 on 2025-12-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('namaste_code', models.CharField(max_length=50)),
                ('icd_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalTerm',
        ),
    ]
